src/index.ts: Stop including object-view-demo.ts
This was causing the following errors:

    ../examples/object-view-demo.ts(204,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(208,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(247,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(306,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(321,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(333,10): error TS2393: Duplicate function implementation.
    ../examples/object-view-demo.ts(343,10): error TS2393: Duplicate function implementation.
    package-view-demo.ts(8,7): error TS2451: Cannot redeclare block-scoped variable 'objectsColWidth'.
    package-view-demo.ts(9,7): error TS2451: Cannot redeclare block-scoped variable 'packagesColWidth'.
    package-view-demo.ts(10,7): error TS2451: Cannot redeclare block-scoped variable 'packagesHeight'.
    package-view-demo.ts(59,10): error TS2393: Duplicate function implementation.
    package-view-demo.ts(67,10): error TS2393: Duplicate function implementation.
    package-view-demo.ts(71,10): error TS2393: Duplicate function implementation.
    package-view-demo.ts(110,10): error TS2393: Duplicate function implementation.
    package-view-demo.ts(118,10): error TS2393: Duplicate function implementation.